os: linux
dist: ubuntu

language: node_js

node_js:
  - "10.15.3"

addons:
  apt:
    packages:
    - libgconf-2-4
    - libxss1
    - libappindicator1
    - libindicator7

cache:
  # cache both npm modules and Cypress binary
  directories:
  - ~/.npm
  - ~/.cache

before_install:
  # Setup Microsoft Repository
  - curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
  - sudo install -o root -g root -m 644 microsoft.gpg /etc/apt/trusted.gpg.d/
  - sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main" > /etc/apt/sources.list.d/microsoft-edge-dev.list'
  - sudo rm microsoft.gpg

  # Update Ubuntu
  - sudo apt-get update && apt-get upgrade -y

  # Install Microsoft Edge
  - sudo apt-get install microsoft-edge-dev -y

before_script:
  # Check Chrome version:
  - google-chrome --version

  # Check Firefox version:
  - firefox --version

  # Check Microsoft Edge Version:
  - microsoft-edge-dev --version  

script:
  # Run Cypress
  - npm install
  - npm run verify
  - npm run test:edge
  
after_success:
  - kill $(jobs -p) || true
notifications:
  email:
  on_failure: change
  on_success: change
