name: Test
on:
  push:
  schedule:
    - cron: '0 */6 * * *'
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      # Replace secrets on the project.

      - name: Replace Cypress Dashboard API Key secret on the package.json
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: '{CYPRESS_DASHBOARD_APIKEY}'
          replace: ${{ secrets.CYPRESS_DASHBOARD_APIKEY }}

      - name: Replace Qase API Token secret on the package.json
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: '{QASE_API_TOKEN}'
          replace: ${{ secrets.QASE_API_TOKEN }}

      # Install NPM dependencies, cache them correctly
      - name: Install dependencies
        run: npm install

      # Run all Cypress tests
      - name: Run the tests
        run: npm run test
