name: End-to-end tests with Cypress
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      # Install, verify and run the Cypress tests. 
      
      # Install cypress
      - run: npm install

      # Verified Cypress
      - run: npm run verify

      # Run the tests on electron headless
      - run: npm run test

      # Analyze the project with Sonar. 
      # The result will be displayed in: https://sonarcloud.io/dashboard?id=estefafdez_cypress-template 
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # Create Mochawesome Report and JSON to get the results
      - run: npm run merge_reports
      - run: npm run generate_mochawesome_report
  
      # Display the results
      - run: chmod +x script/results.sh
      - run: ./script/results.sh 

      - name: Upload artifacts
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: report
          path: report
      # Test run video was always captured, so this action uses "always()" condition
      - uses: actions/upload-artifact@v1
        if: always()
        with:
          name: mochawesome
          path: mochawesome-report