name: End-to-end tests with Cypress
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "0 */2 * * *"
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      # Replace API Key from Qase
      # - name: Replace API Key Qase
      #   uses: jwsi/secret-parser@v1
      #   with:
      #     filename: cypress/config/reporter-config.json
      #     secret-name: apiToken
      #     secret-value: ${{ secrets.QASE_API_TOKEN }}

      # Check the changes
      # - name: Check reporter config file
      #   run: cat cypress/config/reporter-config.json

      # Replace Cypress Dashboard API Key secret on the package.json
      #- run: sed -i "s/{CYPRESS_DASHBOARD_APIKEY}/${{ secrets.CYPRESS_DASHBOARD_APIKEY }}" cypress/package.json > cypress/package.json.changed && mv cypress/package.json.changed cypress/package.json

      - name: sed
        uses: lefherz/action-sed@master
          with:
            args: sed -ie "s/{CYPRESS_DASHBOARD_APIKEY}/${{ secrets.CYPRESS_DASHBOARD_APIKEY }}" cypress/package.json > cypress/package.json.changed && mv cypress/package.json.changed cypress/package.json

      - run: cat cypress/package.json

      # Install NPM dependencies, cache them correctly
      - name: Install dependencies
        run: npm install

      # Run all Cypress tests
      - name: Run the tests
        run: npm run test

      # Analyze the project with Sonar.
      # The result will be displayed in: https://sonarcloud.io/dashboard?id=estefafdez_cypress-template
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # Upload artifacts with the tests results
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: report
          path: report

      # Create mochawesome report and json to get the results
      - name: Merge mochawesome report
        run: npm run merge_reports

      - name: Generate mochawesome report.
        run: npm run generate_mochawesome_report

        # Display the results:
      - name: Display results
        run: chmod +x script/results.sh
      - id: vars
        run: echo ::set-output name=testResult::$(./script/results.sh)

      # Test run video was always captured, so this action uses "always()" condition
      - uses: actions/upload-artifact@v1
        if: always()
        with:
          name: mochawesome
          path: mochawesome-report

      # Publish Test Results
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.6
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: report/*.xml

      # Slack Notify
      - name: Slack Notify
        uses: rtCamp/action-slack-notify@v2.1.2
        if: always()
        env:
          SLACK_CHANNEL: travis-ci
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_ICON: https://github.com/estefafdez/cypress-template/blob/main/script/github.png
          SLACK_USERNAME: "Github Actions"
          SLACK_FOOTER: "Github project: https://github.com/estefafdez/cypress-template"
          SLACK_TITLE: "Test Suite Results:"
          SLACK_MESSAGE: ${{ steps.vars.outputs.testResult }}
